function gvjs_kZ(a){this.m=a.options;this.EX=a.Bn;this.Sh=a.oK;this.pO=a.axes.domain;this.h4=a.axes.target;this.caa=null!=a.baa?a.baa:1;this.cqa=null!=a.bqa?a.bqa:gvjs__;this.iw=this.mf()}gvjs_kZ.prototype.Uy=function(){var a=[];gvjs_s(this.iw,function(b){gvjs_Wc(a,b.F.list)});gvjs_1c(a,function(a,c){return a.stack===c.stack?-gvjs_0c(a.Go,c.Go):gvjs_0c(a.stack,c.stack)});return a};
gvjs_kZ.prototype.sI=function(){var a=[];gvjs_s(this.iw,function(b){gvjs_q(b.groups,function(b,d){null!=b&&gvjs_q(b.uo,function(b,c){gvjs_Wc(a,gvjs_r(b.Rb.Bk,function(a,b){var e=a.shape.data();return a.shape.clone().data({value:e,id:gvjs_QM(gvjs_QM(gvjs_QM(gvjs_QM(gvjs_SM(a.definition.to,a.definition.gF),gvjs_4T,a.definition.qj),gvjs_lw,d),gvjs_Ry,c),gvjs_3T,b+1)})}));gvjs_Wc(a,gvjs_r(b.Rb.Pz,function(a,b){var e=a.shape.data();return a.shape.clone().data({value:e,id:gvjs_QM(gvjs_QM(gvjs_QM(gvjs_QM(gvjs_SM(a.definition.to,
a.definition.gF),gvjs_4T,a.definition.qj),gvjs_lw,d),gvjs_Ry,c),gvjs_3T,-b-1)})}))},this)},this)},this);return a};function gvjs_2ka(a,b){if(1>=a)return[b];var c=0*(b.end-b.start),d=c/(a-1);c=(b.end-b.start-c)/a;var e=[];b=b.start;for(var f=0;f<a;f++)e.push(new gvjs_z(b,b+c)),b+=c+d;return e}
function gvjs_3ka(a,b,c,d){var e={range:b,definition:c,uo:[]},f=gvjs_2ka(c.uo.length,b);gvjs_q(c.uo,function(a,b){var c={definition:a,range:f[b],height:{Bk:0,Pz:0},Rb:{Bk:[],Pz:[]}};e.uo.push(c);gvjs_q(a.Rb,function(a,e){a.to in d.index?d.list[d.index[a.to]].Rb.push(a):(d.index[a.to]=d.list.length,d.list.push({color:null,Xb:a.to,stack:b,Go:e,Rb:[a]}),d.Q3=Math.max(d.Q3,b+1),d.QV=Math.max(d.QV,e+1));e=this.h4[a.CL];var f=e.scale,g=f.scale(f.AC());f=c.range.start;var h=c.height.Bk+g,k=c.range.end-c.range.start,
l=a.value;if(isNaN(l)||null==l)e=null;else{l-=g;var m=l+c.height.Bk;0<=l?c.height.Bk+=l:(h=-c.height.Pz+g,m=-c.height.Pz+l+g,c.height.Pz-=l);a.fu=k/2+c.range.start;a.IHa=m;gvjs_QM(gvjs_SM(a.to,a.gF),gvjs_4T,a.qj);g=new gvjs_y(h,f+k,h+l,f);g.top>g.bottom&&(m=g.top,g.top=g.bottom,g.bottom=m);null===e.range?e.range=new gvjs_z(g.top,g.bottom):(gvjs_ph(e.range,g.top),gvjs_ph(e.range,g.bottom));e=(new gvjs_9A(f,h,k,l)).setData(a)}e&&(0<=gvjs_E(gvjs_2A(e),gvjs_mb)?c.Rb.Bk:c.Rb.Pz).push({definition:a,shape:e})},
this)},a);return e}
function gvjs_4ka(a,b){var c={};if(gvjs_Ic(a,function(a){return 0===a.groups.length}))return{};gvjs_q(a,function(a,b){gvjs_q(a.groups,function(a){c[a.qj]=b})});var d={},e={},f;for(f in b){var g=b[f],h=g.scale;g=gvjs_r(g.columns,function(b){return a[c[b]]});var k={LGa:h.Ii(),type:g[0].type,scale:h,mg:{},groups:[]};e[f]=k;k.type in d||(d[k.type]=f);if(h.Ii())for(var l=0;;l++){var m={uo:[]},n=gvjs_r(g,function(a){return a.groups[l]});if(!gvjs_Hc(n,gvjs_nc))break;gvjs_q(n,function(a){a.ih&&null==m.ih&&
(m.ih=a.ih);gvjs_Wc(m.uo,a.uo)});k.groups.push(m)}else{var p=[];gvjs_q(g,function(a){gvjs_q(a.groups,function(a){var b=gvjs_Zc(p,a,function(a,b){return h.by(a.ih,b.ih)});0>b?gvjs_Qc(p,{ih:a.ih,mg:gvjs_t(a.mg),uo:gvjs_Vc(a.uo)},-(b+1)):gvjs_Wc(p[b].uo,a.uo)})});k.groups=p}}return e}
function gvjs_5ka(a,b,c,d){var e=a.pO[c],f=e.scale;f.Ii()||gvjs_1c(b.groups,function(a,b){a=a.ka?a.ih:f.scale(a.ih);b=b.ka?b.ih:f.scale(b.ih);return gvjs_0c(a,b)});var g=Infinity,h=null;gvjs_q(b.groups,function(a){f.Ii()&&(a.ih=f.add(a.ih),a.ka=!0);a=a.ka?a.ih:f.scale(a.ih);if(null!=a){if(null!==h){var b=a-h;0<b&&b<g&&(g=b)}h=a}});isFinite(g)||(g=1);var k={list:[],index:{},Q3:0,QV:0};c=gvjs_r(b.groups,function(a){var b=a.ka?a.ih:f.scale(a.ih);if(null!=b){var c=g,d=b;b+=c;switch(this.cqa){case gvjs__:d-=
c/2,b-=c/2}c=(b-d)/2;d+=(1-this.caa)*c;b-=(1-this.caa)*c;d=new gvjs_z(d,b);null===e.range?e.range=d.clone():(c=e.range,c.start=Math.min(c.start,d.start),c.end=Math.max(c.end,d.end));return gvjs_3ka(this,d,a,k)}},a);for(var l=0,m=k.Q3;l<m;l++)for(var n=0,p=k.QV;n<p;n++)a.Sh.Ju(String(l),String(n));var q=a.Sh.pe();gvjs_q(k.list,function(a,b){var c=gvjs_ld(gvjs_C(this.m,gvjs_zy+(b+d)+".color",q.Rq(a.stack,a.Go))).hex;a.color=c;gvjs_q(a.Rb,function(a){a.color=c})},a);return{definition:b,F:k,groups:c}}
gvjs_kZ.prototype.mf=function(){var a=gvjs_4ka(this.EX,this.pO),b=0;return gvjs_le(a,function(a,d){a=gvjs_5ka(this,a,d,b);b+=a.F.list.length;return a},this)};function gvjs_lZ(a,b,c,d){gvjs_eV.call(this,a,b,c,d)}gvjs_p(gvjs_lZ,gvjs_eV);gvjs_lZ.prototype.Ei=function(){return gvjs_C(this.options,gvjs_ku,gvjs_3,gvjs_dV)===gvjs_1?gvjs_3:gvjs_1};
gvjs_lZ.prototype.Dna=function(a,b,c,d){function e(a,b){return f?b:a}var f=gvjs_D(this.options,"stacked",!1),g=this.Bi,h=a[String(c.qj)],k=g.getValue(d,c.qj);this.Ei();var l=e([0],c.F),m=[];gvjs_q(e(c.F,[0]),function(a){var e=[],n={};gvjs_q(l,function(l){l=(f?l:a).Os;var m=g.getValue(d,l),p=b[l],q=p.scale,r=p.name;r in n||(e.push({Rb:[]}),n[r]=e.length-1);r=e[n[r]].Rb;q.Ii()&&null!=m&&(0===gvjs_qU(q).length&&q.add("",!0),q.add(m,!0));r.push({qj:c.qj,to:l,gF:d,qO:h.name,CL:p.name,ih:k,THa:m,color:null,
value:p.scale.scale(m),ka:!0})});gvjs_q(e,function(a){m.push(a)})});return{qj:c.qj,ih:k,mg:c.mg,uo:m}};gvjs_lZ.prototype.Cna=function(a,b,c){return{type:this.Bi.Y(c.qj),mg:c.mg,groups:gvjs_r(gvjs_5c(this.Bi.ea()),gvjs_o(this.Dna,this,a,b,c))}};
gvjs_lZ.prototype.HY=function(a,b,c){gvjs_s(a,function(a){a.expand=!1});gvjs_s(b,function(a){a.expand=!0});var d=this.Ei()===gvjs_3,e=d&&gvjs_Hc(gvjs_re(b),function(a){return b[a].Mk===gvjs_lz}),f=d&&gvjs_Hc(gvjs_re(b),function(a){return b[a].Mk===gvjs_tu}),g={},h;for(h in b)gvjs_q(b[h].columns,function(a){g[a]={name:h,scale:b[h].scale}});var k={};for(h in a)gvjs_q(a[h].columns,function(b){k[b]={name:h,scale:a[h].scale}});var l=gvjs_r(this.ZN.Bn,gvjs_o(this.Cna,this,k,g));return new gvjs_kZ({options:this.options,
Bn:l,axes:{domain:a,target:b},oK:c,baa:gvjs_Mi(this.options,"groupSize"),fHa:!d||e,gHa:!d||f})};function gvjs_mZ(a,b){gvjs_hV.call(this,a,b)}gvjs_p(gvjs_mZ,gvjs_hV);gvjs_=gvjs_mZ.prototype;gvjs_.fq=function(a){a.style(gvjs_Dy,0).style(gvjs_Ey,1).style(gvjs_By,.4).style(gvjs_Cy,2);return a};gvjs_.Br=function(a){a.style(gvjs_Dy,null).style(gvjs_Ey,null).style(gvjs_By,null).style(gvjs_Cy,null);return a};gvjs_.rT=function(a){var b=a.data().value.color;this.fq(a).style(gvjs_Ov,b)};gvjs_.kT=function(a){var b=a.data().value.color;this.fq(a).style(gvjs_Ov,gvjs_iV(b,this.VP,this.JB))};
gvjs_.hT=function(a){var b=a.data().value.color;this.Br(a).style(gvjs_Ov,gvjs_jV(b,this.zfa,this.JB))};gvjs_.qT=function(a){var b=a.data().value.color;this.Br(a).style(gvjs_Ov,b)};function gvjs_nZ(a){gvjs_2M.call(this,a)}gvjs_p(gvjs_nZ,gvjs_2M);gvjs_=gvjs_nZ.prototype;gvjs_.Lq=function(){return null};gvjs_.Ih=function(){return gvjs_gV};gvjs_.uq=function(a,b,c,d){a=new gvjs_7T(this,a,b,c,d);a.Nw([gvjs_gu,gvjs_dw,gvjs_oy,gvjs_RT,gvjs_XT,gvjs_Ft,gvjs_Et,gvjs_0l]);return a};gvjs_.Oo=function(a,b){return new gvjs_mZ(a,b)};gvjs_.sn=function(a,b,c,d){return new gvjs_lZ(a,b,c,d)};
gvjs_.Ks=function(a){return[new gvjs_fU([new gvjs_OM(gvjs_0s)]),new gvjs_hU([new gvjs_OM(gvjs_1s),new gvjs_OM(gvjs_2s)],gvjs_C(a,gvjs_ty)===gvjs_Ly),new gvjs_gU([new gvjs_OM(gvjs_0s),new gvjs_OM(gvjs_1s),new gvjs_OM(gvjs_2s),new gvjs_OM(gvjs_0T)]),new gvjs_jU([new gvjs_OM(gvjs_1s)])]};gvjs_.pH=function(a,b){null!=this.jh?this.jh.update(a,b):this.jh=new gvjs_IB(this.container,a,b,[gvjs_tt,gvjs_2T])};gvjs_k(gvjs_lk,gvjs_nZ,void 0);gvjs_nZ.convertOptions=function(a){var b=new gvjs_oi([a]);a=gvjs_BV(a);b=b.Sb(gvjs_Mx);null!=b&&(a.bars=b===gvjs_3?gvjs_1:gvjs_3);return a};gvjs_nZ.prototype.draw=gvjs_nZ.prototype.draw;gvjs_nZ.prototype.clearChart=gvjs_nZ.prototype.Wb;gvjs_nZ.prototype.getSelection=gvjs_nZ.prototype.getSelection;gvjs_nZ.prototype.setSelection=gvjs_nZ.prototype.setSelection;
